<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Positive</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>025e565f-f02c-42af-8fb2-8cc383d4ac84</testSuiteGuid>
   <testCaseLink>
      <guid>35b82e79-45e4-4615-af47-89113e40ff15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Elements/Textbox/Email/Positive/Email Valid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94e890a8-2e47-46b8-a8c8-0ebd3d428173</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e03b3ec3-cadc-4d8b-8e5d-5b9aed51fad5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0e1ffc1-1d6e-4da3-b689-f913abe05b0b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Elements/Textbox/Email/Positive/Using Acceptable Character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5ba90ef-cbe5-4d16-8051-1fc75f05cff3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18d11fa9-770e-4676-8cd5-dbe82a938d1f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed2e575b-cdb2-4a50-9b59-9d21618cb937</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Elements/Textbox/Email/Positive/Using Alphabet</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d479456f-1128-48a3-9356-c5e624a49227</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a62ac3f-f7a1-4735-bc28-f2b9cd6032ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>114711c8-b1d1-430b-8b81-75337954729c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Elements/Textbox/Email/Positive/Using Number</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8584ea10-9e71-4973-aed2-c860622edffc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40ca4a47-cad4-4dae-8892-d7c3cab50147</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
