<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>All</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3efcbb3a-c49a-495f-92e6-333673e4d3a6</testSuiteGuid>
   <testCaseLink>
      <guid>c6090310-c17c-4d7a-bc4b-22cd9b1097af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Elements/Textbox/Fullname/Positive/Fullname Valid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a751e7ef-d0bd-48ef-baf1-e40060f22787</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ab05afa-25fc-4aa7-856d-a492785527f8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c7d9e07e-7321-4d67-b546-88ba89ae3dee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Elements/Textbox/Fullname/Positive/Input Alphabet</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2afef8a6-8cd4-48b5-ad97-309112f8e6ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24a5eab4-dc71-4303-b547-c036e5f02945</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b79690a-246a-49a8-9157-e1d36416a8ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Elements/Textbox/Fullname/Positive/Input Camel Case</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0971c396-37fd-4e3d-9136-db7f04823222</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Elements/Textbox/Fullname/Positive/Input Character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26abbf7a-68ce-42f9-babe-55c714081328</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>339b30c5-5c45-4f86-9225-484157547714</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>28bdd290-aa41-41b1-a771-a8cf704ec1f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Elements/Textbox/Fullname/Positive/Input Combination</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21965bed-17f0-48cd-9f33-6e45fcff8d7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b161e0a9-25ef-4c32-a1f5-745394809440</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9508c604-e425-4493-bb7b-3862d6af5a6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Elements/Textbox/Fullname/Positive/Input Lowercase</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>551e008d-5a94-4c0b-92d2-46dc5fd79873</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Elements/Textbox/Fullname/Positive/Input Number</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a11c0b06-e59e-490a-aefb-36791237b18f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2000225f-2697-47bb-9af2-cbb900883a3d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e8af2363-a383-4bce-87c2-e7f20a617f08</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Elements/Textbox/Fullname/Positive/Input Uppercase</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>3aca173f-cddc-4f23-ba02-d2abb0c55197</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Elements/Textbox/Fullname/Positive/Input Using Space</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b6ea868b-f55b-45d1-9b3f-7e2bb3815283</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Elements/Textbox/Fullname/Negative/Input Only Space</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>250a5f66-ed84-42b2-9e02-451a6c66127c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Elements/Textbox/Fullname/Data-driven Testing/DDT - Fullname</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>409054e3-e62b-41ca-af0e-72100f97a4c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5dec18d-ad50-45a2-9562-f62cee746842</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
